import Head from "next/head";
import { createClient } from "contentful";
import Image from "next/image";
import Header from "../components/Header";
import Process from "../components/Process";
import Services from "../components/Services";
import TopNav from "../components/TopNav";
import Skills from "../components/Skills";
import styles from "../styles/Home.module.css";

export default function Home({ headers, links }) {
  console.log("headers: ", headers);
  console.log("links: ", links);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNav headers={headers} />
        <Header headers={headers} links={links} />
        <Services />
        <Process />
        <Skills />
      </main>
    </>
  );
}
export async function getServerSideProps() {
  console.log("Space: ", process.env.space);
  const client = createClient({
    space: process.env.space,
    accessToken: process.env.accessToken,
  });
  const res = await client.getEntries({ content_type: "protfolio" });
  const links = await client.getEntries({ content_type: "socialMedia" });
  console.log("response: ", links);
  return {
    props: {
      headers: res?.items[0]?.fields,
      links: links?.items,
    },
  };
}
